name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fastapi-car-price-pred:$(date +%s)

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
          image: tiagogdev/my-private-docker-repo
          tags: v1
          dockerfile: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}