name: GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: hw-dev
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-private-docker-repo:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Google Cloud Platform
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}'

      # Gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # Build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # Push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: fastapi-car-price-pred
          region: europe-west1
          image: $IMAGE_NAME

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
        